import React from 'react'
import classes from './LandingPage.module.css'
import Image from 'next/future/image'
import Link from 'next/link'
import LandingImg from '../../Images/header/audience-gffb00a2c7_1920.jpg'

function LandingPage() {
  return (
    <div className={classes.containerWrapper}>
      <Image className={classes.containerImg} src={LandingImg} alt="Children playing football" width="50px" height="50px" layout="fill" />
      <title>GrassRoot Inc.</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/football.ico" />

      <h1 className={classes.title}>GrassRoot</h1>

      <div className={`${classes.visit} ${classes.btn}`}>
        <Link href={{ pathname: `/orncupen/` }}>Besök cup</Link>
      </div>
    </div>
  )
}
export default LandingPage
